# NumPy quickstart [🔗](https://numpy.org/doc/stable/user/quickstart.html)

This code is written for a quick recap on major functions of NumPy using **MNIST** dataset of Scikit-learn. Based on 'NumPy quickstart' document, added and modified code for learning and experimenting.

In [22]:
import numpy as np
import seaborn as sns
from sklearn.datasets import load_digits

images = load_digits().images
target = load_digits().target

## The basics

In [25]:
# .ndim: the number of axes(dimensions) of the array
images.ndim

3

In [27]:
# .shape: the dimensions of the array
images.shape

(1797, 8, 8)

In [29]:
# .size: the total number of elements
images.size

115008

In [33]:
# .dtype
images.dtype

dtype('float64')

In [35]:
# .itemsize: the size in bytes of each element
images.itemsize

8

### Array Creation

In [50]:
# array of zeros
np.zeros((8, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
# array of ones
np.ones((2, 8, 8), dtype=np.int16)

array([[[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1]]], dtype=int16)

In [66]:
# array of random content
## depends on the state of the memory
np.empty((8, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
# create sequences of numbers
np.arange(0, 10, 1.3)

array([0. , 1.3, 2.6, 3.9, 5.2, 6.5, 7.8, 9.1])

In [80]:
# create sequences of number with the number of elements
np.linspace(0, 10, 8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [110]:
np.fromfunction(lambda i, j: i + j, (4, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [112]:
def f(x, y):
    return 10 * x + y

np.fromfunction(f, (4, 3), dtype=float)

array([[ 0.,  1.,  2.],
       [10., 11., 12.],
       [20., 21., 22.],
       [30., 31., 32.]])

### Print

In [85]:
# not skip the central part of array
import sys
np.set_printoptions(threshold=sys.maxsize)

### Basic operations

In [93]:
# matrix product
images[0] @ images[1]

array([[  0.,  91., 220., 443., 448.,  89.,   0.,   0.],
       [  0., 105., 294., 915., 928., 258.,   0.,   0.],
       [  0.,  14.,  94., 594., 624., 235.,   0.,   0.],
       [  0.,   0.,  52., 480., 512., 204.,   0.,   0.],
       [  0.,   0.,  41., 447., 480., 195.,   0.,   0.],
       [  0.,   0.,  53., 529., 560., 219.,   0.,   0.],
       [  0.,  35., 139., 664., 688., 214.,   0.,   0.],
       [  0.,  91., 223., 458., 464.,  92.,   0.,   0.]])

### Indexing, Slicing, and iterating

In [95]:
# Slicing: from start to position 6, exclusive, select every 2nd element
images[0][:6:2]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.]])

In [100]:
# reverse the array
images[0][::-1]

array([[ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.]])

In [108]:
# ... : many colons as needed to produce a complete indexing tuple
images[0][..., 2]

array([ 5., 13., 15., 12.,  8., 11., 14.,  6.])

In [114]:
# ,flat: iterotor over all the elements of the array
for e in images[0].flat:
    print(e)

0.0
0.0
5.0
13.0
9.0
1.0
0.0
0.0
0.0
0.0
13.0
15.0
10.0
15.0
5.0
0.0
0.0
3.0
15.0
2.0
0.0
11.0
8.0
0.0
0.0
4.0
12.0
0.0
0.0
8.0
8.0
0.0
0.0
5.0
8.0
0.0
0.0
9.0
8.0
0.0
0.0
4.0
11.0
0.0
1.0
12.0
7.0
0.0
0.0
2.0
14.0
5.0
10.0
12.0
0.0
0.0
0.0
0.0
6.0
13.0
10.0
0.0
0.0
0.0


## Shape manipulation

### Changing the shape

In [118]:
# .ravel(): returns the array, flattened
images[0].ravel()

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [122]:
# .reshape(): returns the array with a modified shape
images[0].reshape(4, 4, 4)

array([[[ 0.,  0.,  5., 13.],
        [ 9.,  1.,  0.,  0.],
        [ 0.,  0., 13., 15.],
        [10., 15.,  5.,  0.]],

       [[ 0.,  3., 15.,  2.],
        [ 0., 11.,  8.,  0.],
        [ 0.,  4., 12.,  0.],
        [ 0.,  8.,  8.,  0.]],

       [[ 0.,  5.,  8.,  0.],
        [ 0.,  9.,  8.,  0.],
        [ 0.,  4., 11.,  0.],
        [ 1., 12.,  7.,  0.]],

       [[ 0.,  2., 14.,  5.],
        [10., 12.,  0.,  0.],
        [ 0.,  0.,  6., 13.],
        [10.,  0.,  0.,  0.]]])

In [126]:
# .resize(): modifies the array itself
img0 = images[0].copy()
img0.resize((4, 4, 4))
img0

array([[[ 0.,  0.,  5., 13.],
        [ 9.,  1.,  0.,  0.],
        [ 0.,  0., 13., 15.],
        [10., 15.,  5.,  0.]],

       [[ 0.,  3., 15.,  2.],
        [ 0., 11.,  8.,  0.],
        [ 0.,  4., 12.,  0.],
        [ 0.,  8.,  8.,  0.]],

       [[ 0.,  5.,  8.,  0.],
        [ 0.,  9.,  8.,  0.],
        [ 0.,  4., 11.,  0.],
        [ 1., 12.,  7.,  0.]],

       [[ 0.,  2., 14.,  5.],
        [10., 12.,  0.,  0.],
        [ 0.,  0.,  6., 13.],
        [10.,  0.,  0.,  0.]]])

In [128]:
# If a dimension is given as -1, the other dimensions are automatically calculated
img0.reshape(8, -1)

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

### Stacking together different arrays

In [134]:
np.vstack((images[0], images[1]))

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.],
       [ 0.,  0.,  0., 11., 16.,  9.,  0.,  0.],
       [ 0.,  0.,  3., 15., 16.,  6.,  0.,  0.],
       [ 0.,  7., 15., 16., 16.,  2.,  0.,  0.],
       [ 0.,  0.,  1., 16., 16.,  3.,  0.,  0.],
       [ 0.,  0.,  1., 16., 16.,  6.,  0.,  0.],
       [ 0.,  0.,  1., 16., 16.,  6.,  0.,  0.],
       [ 0.,  0.,  0., 11., 16., 10.,  0.,  0.]])

In [136]:
np.hstack((images[0], images[1]))

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0.,  0., 12., 13.,
         5.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.,  0.,  0.,  0., 11., 16.,
         9.,  0.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  0.,  3., 15., 16.,
         6.,  0.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.,  0.,  7., 15., 16., 16.,
         2.,  0.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.,  0.,  0.,  1., 16., 16.,
         3.,  0.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  0.,  1., 16., 16.,
         6.,  0.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.,  0.,  0.,  1., 16., 16.,
         6.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.,  0.,  0.,  0., 11., 16.,
        10.,  0.,  0.]])

In [142]:
# .column_stack(): stacks 1D arrays as columns into a 2D array
## same as .hstack() for 2D arrays
np.column_stack((images[0][0], images[0][1]))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 5., 13.],
       [13., 15.],
       [ 9., 10.],
       [ 1., 15.],
       [ 0.,  5.],
       [ 0.,  0.]])

In [156]:
# View 1D array as a 2D column vector
from numpy import newaxis # alias for None, useful for indexing arrays

images[0][1][:, newaxis]

array([[ 0.],
       [ 0.],
       [13.],
       [15.],
       [10.],
       [15.],
       [ 5.],
       [ 0.]])

In [163]:
# .r_/ .c_: translates slice objects to concatenation along the first/second axis
np.r_[0:4, 7, 9, 15, 4]

array([ 0,  1,  2,  3, 10,  9, 15,  4])

In [183]:
np.c_[np.array([6, 4, 11, 9]), np.zeros(4)]

array([[ 6.,  0.],
       [ 4.,  0.],
       [11.,  0.],
       [ 9.,  0.]])

### Splitting one array into several smaller ones

In [201]:
# np.hsplit(): split an array along its horizontal axis
np.hsplit(images[0], 4)

[array([[0., 0.],
        [0., 0.],
        [0., 3.],
        [0., 4.],
        [0., 5.],
        [0., 4.],
        [0., 2.],
        [0., 0.]]),
 array([[ 5., 13.],
        [13., 15.],
        [15.,  2.],
        [12.,  0.],
        [ 8.,  0.],
        [11.,  0.],
        [14.,  5.],
        [ 6., 13.]]),
 array([[ 9.,  1.],
        [10., 15.],
        [ 0., 11.],
        [ 0.,  8.],
        [ 0.,  9.],
        [ 1., 12.],
        [10., 12.],
        [10.,  0.]]),
 array([[0., 0.],
        [5., 0.],
        [8., 0.],
        [8., 0.],
        [8., 0.],
        [7., 0.],
        [0., 0.],
        [0., 0.]])]

## Copies and views

### View or shallow copy

In [205]:
# .view(): creates a new array object that looks at the smae data
## original array doesn't change when there's modification on the view
img0 = images[0].view()

print(img0 is images[0])

img0 = img0.reshape((4, 16))
print(img0.shape, images[0].shape)

False
(4, 16) (8, 8)


## Advanced indexing and index tricks

In [210]:
# Give indexes for more than one dimension
i = np.array([[0, 1],
              [1, 2]])
j = np.array([[2, 1],
              [3, 3]])

## [[images[0, 2], images[1, 1]], 
##  [images[1, 3], images[2, 3]]]
images[i, j]

array([[[ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
        [ 0.,  0.,  0., 11., 16.,  9.,  0.,  0.]],

       [[ 0.,  7., 15., 16., 16.,  2.,  0.,  0.],
        [ 0.,  0.,  1.,  6., 15., 11.,  0.,  0.]]])

In [254]:
# .argmax(): returns the indices of the maximum values along an axis

# index of the maxima for each series
ind = images[0].argmax(axis=0)
print('ind:', ind)

# values corresponding to the maxima
images[0][ind, range(images[0].shape[1])]

ind: [0 4 2 1 1 1 2 0]


array([ 0.,  5., 15., 15., 10., 15.,  8.,  0.])

array([ 0.,  5., 15., 15., 10., 15.,  8.,  0.])